config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :sessions, only: [:new, :create, :destroy]
  resources :flyers do
    resources :comments, only: [:create, :destroy]
    resources :bookmarks, only: [:create, :destroy]
  end
  
  root to: 'tops#top' # Home page to display list of flyers

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  post 'uploads/:model/:mounted_as/:id/:filename', to: 'uploads#show', as: 'upload'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :flyer
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :flyer
  validates :content, presence: true, length: { maximum: 255 }
end

app/models/flyer.rb
class Flyer < ApplicationRecord
  belongs_to :user
  mount_uploader :picture, PictureUploader
  mount_uploader :item_image, ItemImageUploader
  has_many :comments
  has_many :bookmarks
  has_many :users, through: :bookmarks

  validates :title, presence: true, length: { maximum: 30 }
  validates :requirement, presence: true, length: { maximum: 100 }
  validates :searching_for, presence: true, length: { maximum: 125 }
  validates :gathering_place, presence: true, length: { maximum: 100 }
  validates :picture, presence: true

  acts_as_taggable_on :tags # This line enables tagging
  def process_image(user_uploaded_image_path)
    require 'mini_magick'

    # 画像に画像を挿入
    image_path = Rails.root.join('app', 'assets', 'images', 'sample.png')
    main_image = MiniMagick::Image.open(image_path)
    main_image_copy = main_image.dup
    overlay_image = MiniMagick::Image.open(user_uploaded_image_path)
    overlay_image.format('png')
    overlay_image.resize "716x500"

    result_image = main_image_copy.composite(overlay_image) do |c|
      c.gravity 'NorthWest' # 左上隅を基準に座標を指定する
      c.geometry "+41+132"  # x座標とy座標を指定
    end

    # 画像に文字列を挿入
    result_image.combine_options do |c|
      c.gravity "Center"
      c.pointsize "50"
      c.font Rails.root.join('app', 'assets', 'fonts', 'Nasu-Regular-20200227.ttf').to_s
      c.fill "black"
    end

    # 結果の画像を保存
    result_image_path = Rails.root.join('tmp', 'final_image.png')
    result_image.write result_image_path

    # Flyerオブジェクトのbackground_imageに結果の画像をセット
    File.open(result_image_path) do |file|
      self.item_image = file
    end
  end
end

app/models/flyer_tag.rb
class FlyerTag < ApplicationRecord
  belongs_to :flyer
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  has_many :flyers, foreign_key: :user_id
  has_many :comments
  has_many :bookmarks
  has_many :bookmark_flyers, through: :bookmarks, source: :flyer

  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, confirmation: true
  validates :name, presence: true
  #validates :profile, presence: true
  #validates :sns_account, presence: true
  def own?(resource)
    self.id == resource.user_id
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login

  private

  def not_authenticated
    redirect_to login_path, danger: "ログインしてください"
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def create
    bookmark = current_user.bookmarks.build(flyer_id: params[:flyer_id])
    bookmark.save
    redirect_to bookmark.flyer, notice: 'Bookmark was successfully created.'
  end

  def destroy
    bookmark = Bookmark.find_by(flyer_id: params[:flyer_id], user_id: current_user.id)
    bookmark.destroy
    redirect_to bookmark.flyer, notice: 'Bookmark was successfully destroyed.'
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = current_user.comments.build(comment_params)
    if @comment.save
      redirect_to @comment.flyer, notice: 'Comment was successfully created.'
    else
      redirect_to @comment.flyer, alert: 'Comment failed to post.'
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to @comment.flyer, notice: 'Comment was successfully destroyed.'
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :flyer_id)
  end
end

app/controllers/flyers_controller.rb
class FlyersController < ApplicationController
  before_action :set_flyer, only: [:show, :edit, :update, :destroy]
  before_action :require_login

  def index
    @flyers = Flyer.all.page(params[:page])
  end

  def new
    @flyer = Flyer.new
  end

  def create
    @flyer = current_user.flyers.build(flyer_params)
    @flyer.user = current_user
    user_uploaded_image_path = @flyer.picture.path
    result_image = @flyer.process_image(user_uploaded_image_path) # 画像にテキストを挿入
    if @flyer.save
      redirect_to flyer_path(@flyer), notice: 'Flyer was successfully created.'
    else
      render :new
    end
  end

  def show; end

  def edit; end

  def update
      @flyer.user = current_user
    user_uploaded_image_path = @flyer.picture.path
    result_image = @flyer.process_image(user_uploaded_image_path) # 画像にテキストを挿入

    if @flyer.update(flyer_params)
      redirect_to flyer_path(@flyer), notice: 'Flyer was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    flyer = current_user.flyers.find(params[:id])
    flyer.destroy!
    redirect_to flyers_path, notice: 'Flyer was successfully destroyed.', status: :see_other
  end

  private

  def set_flyer
    @flyer = Flyer.find(params[:id])
  end

  def flyer_params
    params.require(:flyer).permit(:title, :requirement, :searching_for, :gathering_place, :picture, :picture_cache, :picture_two, :picture_tow_cache, :item_image_cache, :tag_list)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: %i[create new]

  def new; end

  def create
    @user = login(params[:email],params[:password])
    if @user
      redirect_to flyers_path, notice: 'Logged in.'
    else
      flash.now.alert = 'Email or password was invalid.'
      render :new
    end
  end

  def destroy
    logout
    redirect_to root_path, notice: 'Logged out.', status: :see_other
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def top; end
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  def show
    model_name = params[:model].camelize.constantize
    mounted_as = params[:mounted_as].to_sym
    id = params[:id]
    filename = params[:filename]

    # モデルを取得
    model = model_name.find(id)

    # アップローダーを初期化
    uploader = model.send(mounted_as)

    # 画像の送信
    send_file uploader.path(filename), type: uploader.file.content_type, disposition: 'inline'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_action :require_login, only: %i[create new]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/flyers/_form.html.erb
<div style="display: flex; justify-content: center; color: gray;">
<%= form_with(model: flyer, local: true) do |form| %>
  <% if flyer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(flyer.errors.count, "error") %> prohibited this flyer from being saved:</h2>
      <%= render 'shared/error_messages', object: flyer %>
    </div>
  <% end %>

  <div class="field" style="display: flex; flex-flow: column;">
    <%= form.label '探しもの' %>
    <%= form.text_area :title %>
  </div>

  <div class="field" style="display: flex; flex-flow: column;">
    <%= form.label '詳細' %>
    <%= form.text_area :requirement %>
  </div>

  <div class="field" style="display: flex; flex-flow: column;">
    <%= form.label '種類' %>
    <%= form.text_area :searching_for %>
  </div>

  <div class="field" style="display: flex; flex-flow: column;">
    <%= form.label '届けてほしい場所' %>
    <%= form.text_area :gathering_place %>
  </div>

  <div class="field" style="display: flex; flex-flow: column;">
    <%= form.label :チラシに貼り付ける画像%><span style="color: red;">※必須</span>
    <%= form.file_field :picture %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
  <span style="font-size: 10px; color: red;">※画像を選択しないとエラーが発生します</span>
  <span style="font-size: 10px; color: red;">※編集時に画像は変更できません</span>
<% end %>
</div>

app/views/flyers/edit.html.erb
<h1>Edit Flyer</h1>
<%= render 'form', flyer: @flyer %>
<%= link_to 'Show', @flyer %> |
<%= link_to 'Back', flyers_path %>

app/views/flyers/index.html.erb
<h1 style="margin-top: 5em">Flyers</h1>
<% @flyers.each do |flyer| %>
  <p style="display: flex; justify-content: center; flex-flow: column;">
  <span style="color: gray;">タイトル：</span><%= link_to flyer.title, flyer %>
  <% if flyer.item_image? %>
    <%= image_tag flyer.item_image.url, style: 'margin: auto;', id: 'preview', size: '200x300'  %>
  <% end %>
  <% if current_user.own?(flyer) %>
    <%= link_to '削除', flyer_path(flyer), style: "color: red;", data: { turbo_method: :delete, turbo_confirm: "本当に削除しますか？"} %>
  <% end %>
  </p>
<% end %>
<%= link_to 'New Flyer', new_flyer_path %>
  <%= paginate @flyers %>

app/views/flyers/new.html.erb
<h1>New Flyer</h1>
<%= render 'form', flyer: @flyer %>
<%= link_to 'Back', flyers_path %>

app/views/flyers/show.html.erb
<div style="margin-top: 10em; color: gray;">
<% if @flyer.item_image? %>
  <%= image_tag @flyer.item_image.url, style: 'padding: 2em;', id: 'preview'  %>
<% end %>
<ul style="font-size: 25px;">
  <li>探しているもの：<%= @flyer.title %></li>
  <li>詳細：<%= @flyer.requirement %></li>
  <li>種類：<%= @flyer.searching_for %></li>
  <li>届けてほしい場所：<%= @flyer.gathering_place %></li>
</ul>
<!-- Add more fields as needed -->
<%= link_to 'Edit', edit_flyer_path(@flyer) %> |
<%= link_to 'Back', flyers_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <style>
button{
  background-color: transparent;
  border: none;
  cursor: pointer;
  outline: none;
  padding: 0;
  appearance: none;
  color: white;
}
    a{
      color: white;
      text-decoration: none;

    }

    .btn--green,
    a.btn--green {
      color: #fff;
      border: 1px solid #008000;
      border-radius: 0.5rem;
      /*コレ*/display: flex;
                       /*コレ*/align-items: center;
    }
    .btn--green:hover,
    a.btn--green:hover {
      color: #fff;
      background: #008000;
      border-radius: 0.5rem;
      /*コレ*/display: flex;
                       /*コレ*/align-items: center;
    }
    ul{
      list-style: none;
    }
    textarea{
      background: #c0c0c0;
      border-radius: 15px;
    }
    </style>
  </head>

  <body style="background: #c0c0c0; color: white; ">
    <header>
      <%= render 'shared/header' %>
    </header>
    <div style="margin-top: 7em">
    <main style="
                 margin: auto;
                 background: #d3d3d3;
                 color: #fff;
                 text-align: center;
                 width: 900px;">
      <%= yield %>
    </main>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this <%= object.class.name.downcase %> from being saved:</h2>
    <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_header.html.erb
<nav style="background-color: #3cb371; width: 100%;  position: fixed; top: 0; left: 0;">
  <% if logged_in? %>
    <ul style="display: flex; list-style: none; align-items: stretch;">
      <li>
        <h1>探しています</h1> 
      </li>
      <li style="margin-left: 12em;", class="btn btn--green">
        <%= link_to '探しもの一覧', flyers_path %>
      </li>
      <li style="margin-left: 1em;", class="btn btn--green">
        <%= link_to '探しもの新規作成', new_flyer_path %>
      </li>
      <li style="margin-left: 1em;", class="btn btn--green">
        <%= button_to 'ログアウト', logout_path, method: :delete, data: { turbo_method: 'delete', confirm: 'ログアウトしますか' } %>
      </li>
      <li style="margin-left: 6em;">
        お名前：<%= current_user.name %>
      </li>
    </ul>
  <% else %>
    <%= link_to '新規登録', signup_path %>
    <%= link_to 'ログイン', login_path %>
  <% end %>
</nav>

app/views/tops/top.html.erb
<%= link_to '新規登録', signup_path %>
<%= link_to 'ログイン', login_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <%= render 'shared/error_messages', object: @user %>
    </div>
  <% end %>

    <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

 <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

 <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit User</h1>
<%= render 'form', user: @user %>
<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/new.html.erb
<h1>New User</h1>
<%= render 'form', user: @user %>
<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>
<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>
<!-- Add more fields as needed -->
<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>